# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  imageName: 'pipelines-javascript-docker'

steps:
#- script: npm i
#  displayName: 'Installing dependencies'
#- script: ng build --configuration production --source-map=false --subresource-integrity --output-path=dist/full-stack
#  displayName: 'Building project'
#- script: npm run-script build-prod
#  displayName: 'Building project'
#- script: docker build -f ./docker/Dockerfile -t babuafi/$(projectName):0.0.1 .
#  displayName: 'Docker build'
- script: docker login -u$(dockerUser) -p$(dockerPass)
  displayName: 'Docker Hub login'
- powershell: |
    $version = (Get-Content .\version)
    echo "$version"
    echo "##vso[task.setvariable variable=version]$version"
  displayName: 'Read version'
- script: |
    docker push babuafi/$(projectName):$(version)
  displayName: 'Docker push'
- powershell: |
    $file = "version"
    $fileVersion = [version](Get-Content $file | Select -First 1)
    $newVersion = "{0}.{1}.{2}" -f $fileVersion.Major, $fileVersion.Minor, ($fileVersion.Path + 1)
    $newVersion | Set-Content $file
    echo "$fileVersion -> $newVersion"
  displayName: 'Bump version'
