# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- script: npm i
  displayName: 'Installing dependencies'
- script: ng build --configuration production --source-map=false --subresource-integrity --output-path=dist/full-stack
  displayName: 'Building project'
#- script: npm run-script build-prod
#  displayName: 'Building project'
- powershell: |
    $version = (Get-Content .\version)
    echo "$version"
    echo "##vso[task.setvariable variable=version]$version"
  displayName: 'Read version'
- script: docker build -f ./docker/Dockerfile -t babuafi/$(projectName):$(version) -t babuafi/$(projectName):latest .
  displayName: 'Docker build'
- script: docker login -u$(dockerUser) -p$(dockerPass)
  displayName: 'Docker Hub login'
- script: |
    docker push babuafi/$(projectName):$(version)
    docker push babuafi/$(projectName):latest
  displayName: 'Docker push'
- powershell: |
    $file = "version"
    $fileVersion = (Get-Content $file | Select -First 1).Split(".")
    $fileVersion[2] = [int]$fileVersion[2] + 1
    $newVersion = $fileVersion -join "."
    $newVersion | Set-Content $file
    echo "$newVersion"
  displayName: 'Bump version'
- powershell: |
    git config --global user.name "$(gitUserName)"
    git config --global user.email "$(gitUserEmail)"
    git add version
    git commit -m "[Bump] version to: ${newVersion} [***NO_CI***]"
  displayName: 'Create and Git commit new version'
- powershell: |
    git remote set-url origin https://$(gitUserName):$(gitToken)@github.com/bbarn3y/2022-2023-1-full-stack-frontend.git
    git fetch origin master
    git push origin HEAD:master
  displayName: 'Git push'
