# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  imageName: 'pipelines-javascript-docker'

steps:
#- script: npm install -g @angular/cli
#  displayName: 'Installing Angular CLI'
#- script: npm i
#  displayName: 'Installing dependencies'
- script: sudo ng build --configuration production --source-map=false --subresource-integrity --output-path=dist/full-stack
  displayName: 'Building project'
- script: docker build -f ./docker/Dockerfile -t babuafi/@{projectName}:$(<version) .
  displayName: 'Docker build'
- script: docker push babuafi/@{projectName}:$(<version)
  displayName: 'Docker push'
