# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-latest'

container: ubuntu:18.04

trigger:
- master

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- script: printenv
  displayName: 'Print environment'
#- script: npm install -g @angular/cli
#  displayName: 'Installing Angular CLI'
- script: npm i
  displayName: 'Installing dependencies'
#- script: ng build --configuration production --source-map=false --subresource-integrity --output-path=dist/full-stack
#  displayName: 'Building project'
- script: npm run-script build-prod
  displayName: 'Building project'
- script: docker build -f ./docker/Dockerfile -t babuafi/$(projectName):0.0.1 .
  displayName: 'Docker build'
- script: docker push babuafi/$(projectName):0.0.1
  displayName: 'Docker push'
